name: CI

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lib
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version-file: .deno-version

      - run: deno task check
        env:
          DENO_NO_PACKAGE_JSON: 1

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: 'npm'

      - run: npm ci

      - run: npx turbo run check build --filter=docs
        env:
          COREPACK_ENABLE_STRICT: '0'
